name: Create Repository Secret

on:
  workflow_dispatch:
    inputs:
      secret_key:
        type: string
        description: Name of the secret's key
      secret_value:
        type: string
        description: value of the secret
      port_payload:
        required: false
        description:
          Port's payload, including details for who triggered the action and
          general context (blueprint, run id, etc...)
        type: string

jobs:
  create_secret:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        run: echo "My workflow is triggered"
        
      - name: UPSERT Entity
        uses: port-labs/port-github-action@v1
        with:
          identifier: ${{ inputs.secret_key }}
          title: ${{ inputs.secret_key }}
          team: "[]"
          icon: DefaultBlueprint
          blueprint: ${{ fromJson(inputs.port_payload).context.blueprint }}
          properties: |-
            {
              "secret_key": "${{ inputs.secret_key }}",
              "secret_value": "${{ inputs.secret_value }}"
            }
          relations: "{}"
          clientId: ${{ secrets.Gw0jJs1nzr50pC4AotjuzQKqHE4Rcp9k }}
          clientSecret: ${{ secrets.pAdTFPuUVAyAHKqhlvX4GN3HMNndKkFxdYxYOeavAYM4S9eqJIQRtikH4UbCyKW1 }}
          operation: UPSERT
          runId: ${{ fromJson(inputs.port_payload).context.runId }}
