name: Update Port Entity

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-port-entity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Port Entity
        uses: port-labs/port-github-action@v1
        with:
	        
          blueprint: "service"
          entity-id: "Test"
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          properties: '{"p_rcount_githubupdate": "5"}'
